### PR TITLE
THECONSOLE-8533

### PR DESCRIPTION
**Pull request by anvesh-makey**
THECONSOLE-8533 Changes for braintree preauth service.

### CODE REVIEW

**Comment by anvesh-makey** [comment]
@jotpal 
Transaction failed is not an error. Its the status of the transaction so logically its not an exception or an error. So returning 200 is fine in this case.
As discussed and agreed in the grooming with Umair & Sumit, error handling will be implemented in a different story. This story is to handle “approved” and “declined” scenarios for a preauth transactions.

**Comment by jotpal** [comment]
I thought we already went through this...Anyways, in your case 4xx and 5xx will never be used...
E.g. if client has sent invalid data/amount/nonce that should fall under 400 Bad Request (client error) and not 200. On the same lines if we have application level errors we should return 500 and not 200.

The idea behind status code is to return Client side or server side error code. Returning 200 for failure scenarios will mean the client has to do further checks to figure out the result.

**Comment by anvesh-makey** [comment]
@jotpal 
Transaction declined is not an application error. Its still a valid transaction, so 500 codes doesn’t apply here technically.

**Comment by jotpal** [comment]
@anvesh-makey 

Agree, so we have to check which category does it fall into...did the client send the bad data or something else happened...based on that lets map it to some 4xx or 5xx error.

**Comment by anvesh-makey** [comment]
@jotpal 
The scenario currently implemented is a transaction decline, nothing to do with bad data or anything. A recorded transaction will be created in this case which has a valid status so it can't be 4xx or 5xx errors. The error handling scenarios will be implemented in a different story.

**Comment by jotpal** [comment]
Just for record - I'm not fully convinced with the way we are handling the failure, plus not consistent with other MS. But if you are confident about this approach, then will go with it.

**Pull request merged**
